config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  
  # Defines the root path route ("/")
  root "categories#index"
  resources :venues
  resources :categories
  get '/dashboard', to: 'static_pages#dashboard'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
    validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum :profile, {
    normal: 0,
    admin: 1,
    supervisor: 2
  }
end

app/models/venue.rb
class Venue < ApplicationRecord
    validates :name, presence: true
    validates :address, presence: true
    validates :capacity, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :get_category, only: [:show, :edit, :destroy]

    def index
        @categories = Category.all
        respond_to do |format|
            format.html {render :index}
            format.json { render json: @categories}
        end
    end

    def show
    end

    def new
        @category = Category.new
    end

    def edit
    end

    def update
        category = Category.find params[:id]
        if category.update(name: category_params)
            redirect_to category, notice: 'Categoría actualizada con éxito'
        else
            render 'edit'
        end
    end

    def create
        cat = Category.new( name: category_params)
        if cat.save
            redirect_to category_path(cat), notice: 'Categoría creada con éxito'
            # redirect_to cat, notice: 'Categoría creada con éxito' es lo mismo
        else
            redirect_to new_category_path, alert: 'No se pudo crear la categoría'
        end
    end

    def destroy
        @category.destroy
        redirect_to categories_path
    end

    private
        def category_params
            params.require(:category).permit(:name)
        end

        def get_category
            @category = Category.find params[:id]
        end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
    def home
    end

    def dashboard
    end
end

app/controllers/venues_controller.rb
class VenuesController < ApplicationControllers
  before_action :set_venue, only: %i[ show edit update destroy ]

  # GET /venues or /venues.json
  def index
    @venues = Venue.all
  end

  # GET /venues/1 or /venues/1.json
  def show
  end

  # GET /venues/new
  def new
    @venue = Venue.new
  end

  # GET /venues/1/edit
  def edit
  end

  # POST /venues or /venues.json
  def create
    @venue = Venue.new(venue_params)

    respond_to do |format|
      if @venue.save
        format.html { redirect_to venue_url(@venue), notice: "Venue was successfully created." }
        format.json { render :show, status: :created, location: @venue }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @venue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /venues/1 or /venues/1.json
  def update
    respond_to do |format|
      if @venue.update(venue_params)
        format.html { redirect_to venue_url(@venue), notice: "Venue was successfully updated." }
        format.json { render :show, status: :ok, location: @venue }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @venue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /venues/1 or /venues/1.json
  def destroy
    @venue.destroy

    respond_to do |format|
      format.html { redirect_to venues_url, notice: "Venue was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_venue
      @venue = Venue.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def venue_params
      params.require(:venue).permit(:name, :address, :capacity)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/venues_helper.rb
module VenuesHelper
end

app/views/categories/_form.html.erb
<div class="container form-group">
    <div class="row">
    <%= form_with model: @category do |form| %>
        <%= form.text_field :name, placeholder: 'Ingresa el nombre', class: 'form-control' %>
        <%= form.submit 'Guardar', class: 'btn btn-success' %>
    <% end %>
    </div>
</div>

app/views/categories/edit.html.erb
<div class="container">
    <div class="row">
        <h1>Editar Categoría</h1>
    </div>
</div>

<%= render 'form' %>
<br>
<div class="container">
    <%= link_to 'Atrás', categories_path, class: 'btn btn-primary' %>
</div>

app/views/categories/index.html.erb
<div class="container">
    <h1>Lista de categorías</h1>
</div>

<div class="container">
    <% if user_signed_in? && current_user.supervisor? %>
        <p><%= current_user.email %></p>
    <% end %>
</div>

<div class="container">
    <ul>
        <% @categories.each do |category| %>
        <li><%= link_to category.name, category %> | <%= link_to 'Editar', edit_category_path(category) %> | <%= link_to 'Eliminar', category, data: { turbo_method: :delete, turbo_confirm: 'Estás seguro?' } %></li>
        <% end %>
    </ul>
</div>

<div class="container">
    <div class="row">
        <%= link_to 'Nueva', new_category_path, class: 'btn btn-primary col-md-2 offset-md-4' %>
    </div>
</div>

app/views/categories/new.html.erb
<div class="container">
    <div class="row">
        <h1>Nueva Categoría</h1>
    </div>
</div>

<%= render 'form' %>

app/views/categories/show.html.erb
<h1><%= @category.name %></h1>

<%= link_to 'Back', categories_path, class: 'btn btn-primary' %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <%= link_to 'Events', root_path, class: 'navbar-brand' %>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
            <%= link_to 'Home', root_path, class: 'nav-link active' %>
            </li>
            <li class="nav-item">
                <%= link_to 'Categorías', categories_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
                <%= link_to 'Ubicaciones', venues_path, class: 'nav-link' %>
            </li>
        </ul>
        <form class="d-flex">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
        </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EventsApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <div class="container">
      <% if user_signed_in?%>
          <p>Hola <%= current_user.email %></p>
      <% end %>
  </div>
    <% if alert %>
      <div class="alert alert-danger" role="alert">
        <%= alert %>
      </div>
    <% end  %>
    <% if notice %>
      <div class="alert alert-success" role="alert">
        <%= notice %>
      </div>
    <% end  %>
    <%= yield %>
  </body>
</html>

app/views/static_pages/dashboard.html.erb
<div class="container">
    <h1>Dashboard</h1>
</div>

<div class="container">
    <div id="categories">
    </div>
</div>

<div class="container">
    <%= link_to 'Cargar', '#', class: 'btn btn-primary', id: 'cargar-ajax' %>
</div>

<script>
    let btn = document.getElementById('cargar-ajax');
    btn.addEventListener('click', event => {
        event.preventDefault();
        console.log('Impreso desde la función');
        let categories = document.getElementById('categories');

        fetch('/categories.json', {
            headers: {
                'X-Requested-With': 'XMLHttpRequest'
            }
        })
            .then(response => response.text())
            .then(x => categories.innerHTML = x)
    });
</script>

app/views/static_pages/home.html.erb
HOME

app/views/venues/_form.html.erb
<%= form_with(model: venue) do |form| %>
  <% if venue.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(venue.errors.count, "error") %> prohibited this venue from being saved:</h2>

      <ul>
        <% venue.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :address, style: "display: block" %>
    <%= form.text_field :address %>
  </div>

  <div>
    <%= form.label :capacity, style: "display: block" %>
    <%= form.text_field :capacity %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/venues/_venue.html.erb
<div id="<%= dom_id venue %>">
  <p>
    <strong>Name:</strong>
    <%= venue.name %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= venue.address %>
  </p>

  <p>
    <strong>Capacity:</strong>
    <%= venue.capacity %>
  </p>

</div>

app/views/venues/edit.html.erb
<h1>Editing venue</h1>

<%= render "form", venue: @venue %>

<br>

<div>
  <%= link_to "Show this venue", @venue %> |
  <%= link_to "Back to venues", venues_path %>
</div>

app/views/venues/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Venues</h1>

<div id="venues">
  <% @venues.each do |venue| %>
    <%= render venue %>
    <p>
      <%= link_to "Show this venue", venue %>
    </p>
  <% end %>
</div>

<%= link_to "New venue", new_venue_path %>

app/views/venues/new.html.erb
<h1>New venue</h1>

<%= render "form", venue: @venue %>

<br>

<div>
  <%= link_to "Back to venues", venues_path %>
</div>

app/views/venues/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @venue %>

<div>
  <%= link_to "Edit this venue", edit_venue_path(@venue) %> |
  <%= link_to "Back to venues", venues_path %>

  <%= button_to "Destroy this venue", @venue, method: :delete %>
</div>